[dependencies]
clap = { default-features = false, features = ["derive", "help", "std", "usage"], optional = true, version = "4.4" }
dotenv = { default-features = false, optional = true, version = "0.15" }
tokio = { default-features = false, features = ["io-std", "io-util", "macros", "net", "rt-multi-thread"], version = "1.35" }
wtx = { default-features = false, features = ["tokio"], path = "../wtx" }

[features]
default = []
embed-migrations = ["clap", "tokio/fs", "wtx/sm", "wtx/std"]
sm = ["clap", "wtx/postgres", "wtx/sm", "wtx/std"]
sm-dev = ["dotenv", "sm", "wtx/_tracing-subscriber", "wtx/sm-dev"]
web-socket = ["clap", "wtx/web-socket-handshake"]

[package]
authors = ["Caio Fernandes <c410.f3r@gmail.com>"]
categories = ["asynchronous", "command-line-interface", "gui"]
description = "Different user interfaces for WTX"
documentation = "https://docs.rs/wtx-ui"
edition = "2021"
keywords = ["io", "network", "websocket"]
license = "Apache-2.0"
name = "wtx-ui"
readme = "README.md"
repository = "https://github.com/c410-f3r/wtx"
version = "0.1.0"

[package.metadata.docs.rs]
all-features = true
